/**
 * Role information — concise descriptions and key tasks for common job titles.
 *
 * Used by the tooltip overlay: when a user hovers over a job title in the
 * results table or a recommended-job pill in the analysis panel, we normalise
 * the title, match it against this registry, and show a pop-up with the role
 * summary and key task bullets.
 *
 * Each entry defines:
 *   matches  — normalised strings to try (longest first wins); the system
 *              checks whether the normalised job title CONTAINS any of these
 *   title    — canonical display name shown in the tooltip header
 *   summary  — 2–3 sentence explanation of what the role does
 *   tasks    — 5–6 key day-to-day responsibilities
 */

const ROLES = [
  // ------------------------------------------------------------------ IT / Engineering
  {
    matches: ['software architect', 'solutions architect'],
    title: 'Software Architect',
    summary: 'Defines the high-level structure of software systems — selecting technologies, establishing patterns, and setting the standards that the development team implements. Acts as the technical authority on major design decisions.',
    tasks: [
      'Design system architecture and select the technology stack',
      'Define coding standards, design patterns, and architectural guidelines',
      'Review technical designs and code for architectural compliance',
      'Evaluate new technologies and integration approaches',
      'Mentor senior engineers on architectural trade-offs',
      'Collaborate with product, infrastructure, and security teams',
    ],
  },
  {
    matches: ['site reliability engineer', 'sre'],
    title: 'Site Reliability Engineer (SRE)',
    summary: 'Applies software engineering principles to operations problems, ensuring production systems are highly available, performant, and scalable. Bridges the gap between development and operations through automation and observability.',
    tasks: [
      'Define and track SLOs, SLIs, and error budgets with engineering teams',
      'Build and maintain observability stacks (Prometheus, Grafana, PagerDuty)',
      'Automate operational toil with scripts, tooling, and runbooks',
      'Lead post-incident reviews and drive follow-up remediation',
      'Capacity-plan and scale cloud infrastructure proactively',
      'Collaborate with developers on reliability and performance requirements',
    ],
  },
  {
    matches: ['machine learning engineer', 'ml engineer', 'ai engineer'],
    title: 'Machine Learning / AI Engineer',
    summary: 'Develops, trains, and deploys machine learning models that power intelligent product features. Bridges data science research and production software engineering, ensuring models run reliably and efficiently at scale.',
    tasks: [
      'Build and evaluate ML models (classification, regression, NLP, computer vision)',
      'Set up MLOps pipelines for training, versioning, and deployment',
      'Monitor model drift and retrain models as data distributions shift',
      'Collaborate with data scientists on feature engineering and experimentation',
      'Optimise model performance, inference latency, and serving cost',
      'Document model behaviour, limitations, and evaluation metrics',
    ],
  },
  {
    matches: ['data scientist'],
    title: 'Data Scientist',
    summary: 'Uses statistical analysis, machine learning, and domain knowledge to extract insights from complex datasets. Helps the business make evidence-based decisions by turning data into actionable findings.',
    tasks: [
      'Define and test hypotheses using statistical methods and A/B experiments',
      'Build predictive and prescriptive models using Python / R',
      'Explore and visualise datasets to surface hidden patterns',
      'Communicate findings clearly to non-technical stakeholders',
      'Collaborate with data engineers on data quality and feature availability',
      'Deploy models to production in partnership with ML engineers',
    ],
  },
  {
    matches: ['data engineer'],
    title: 'Data Engineer',
    summary: 'Builds and maintains the data pipelines, warehouses, and lakes that enable analytics and reporting. Turns raw data from multiple sources into reliable, queryable datasets for analysts and scientists.',
    tasks: [
      'Design and build ETL/ELT pipelines (Airflow, dbt, Spark)',
      'Model data warehouses (Snowflake, BigQuery, Redshift, Databricks)',
      'Ensure data quality, freshness, lineage, and documentation',
      'Work with analysts and scientists to understand reporting requirements',
      'Optimise SQL query performance and storage costs',
      'Set up data cataloguing, access controls, and governance policies',
    ],
  },
  {
    matches: ['data analyst', 'business intelligence analyst', 'bi analyst', 'business analyst data'],
    title: 'Data Analyst / BI Analyst',
    summary: 'Turns business questions into data insights by querying databases, building dashboards, and presenting findings to stakeholders. Acts as the primary link between raw data and business decision-making.',
    tasks: [
      'Write SQL queries and build data models to answer business questions',
      'Create interactive dashboards and reports (Power BI, Tableau, Looker)',
      'Define KPIs and track key business metrics over time',
      'Present insights and recommendations to non-technical stakeholders',
      'Identify trends, anomalies, and growth opportunities in the data',
      'Collaborate with data engineers to improve data quality and coverage',
    ],
  },
  {
    matches: ['cybersecurity', 'security analyst', 'security engineer', 'information security'],
    title: 'Cybersecurity Specialist',
    summary: 'Protects an organisation\'s systems, networks, and data from unauthorised access, attacks, and breaches. Combines proactive threat assessment with reactive incident response to maintain a strong security posture.',
    tasks: [
      'Conduct vulnerability assessments and penetration tests',
      'Monitor SIEM systems and investigate security alerts',
      'Respond to and contain security incidents and breaches',
      'Implement and review security controls and access policies',
      'Ensure compliance with standards (ISO 27001, NIS2, GDPR)',
      'Train employees on security awareness and phishing recognition',
    ],
  },
  {
    matches: ['cloud engineer', 'cloud infrastructure'],
    title: 'Cloud Engineer',
    summary: 'Designs, deploys, and manages cloud-based infrastructure on platforms such as AWS, Azure, or GCP. Focuses on reliability, cost optimisation, and security at scale.',
    tasks: [
      'Architect cloud solutions across compute, storage, networking, and security',
      'Write infrastructure-as-code (Terraform, CloudFormation, Bicep)',
      'Manage IAM roles, VPCs, and network security groups',
      'Optimise cloud spend with reserved instances and right-sizing',
      'Implement disaster-recovery and high-availability architectures',
      'Support migration of on-premises workloads to the cloud',
    ],
  },
  {
    matches: ['devops engineer', 'devops'],
    title: 'DevOps Engineer',
    summary: 'Bridges development and operations by automating the build, test, deploy, and monitor lifecycle of software. Designs the infrastructure and pipelines that let teams ship code safely and frequently.',
    tasks: [
      'Design and maintain CI/CD pipelines (Jenkins, GitHub Actions, GitLab)',
      'Manage containerised workloads with Docker and Kubernetes',
      'Provision cloud infrastructure using Terraform or Ansible',
      'Monitor system health with Prometheus, Grafana, and alerting stacks',
      'Implement security scanning, secrets management, and audit logging',
      'Lead post-incident reviews and drive reliability improvements',
    ],
  },
  {
    matches: ['embedded systems engineer', 'firmware engineer', 'embedded software'],
    title: 'Embedded Systems Engineer',
    summary: 'Develops firmware and low-level software for microcontrollers, FPGAs, and dedicated hardware, typically for automotive, industrial, or consumer electronics applications. Works at the boundary of software and hardware.',
    tasks: [
      'Write firmware in C/C++ for bare-metal and RTOS targets',
      'Implement hardware abstraction layers and device drivers',
      'Debug hardware and software interactions with oscilloscopes and logic analysers',
      'Ensure timing, memory, and power constraints are met',
      'Work with hardware engineers on board bring-up and integration testing',
      'Follow functional safety standards (AUTOSAR, IEC 61508, ISO 26262)',
    ],
  },
  {
    matches: ['network engineer', 'network administrator'],
    title: 'Network Engineer',
    summary: 'Designs, implements, and maintains the computer networks (LAN, WAN, Wi-Fi, VPN) that connect an organisation\'s systems and users. Ensures connectivity is fast, reliable, and secure.',
    tasks: [
      'Design and configure routers, switches, and firewalls',
      'Implement network monitoring and alerting tools',
      'Troubleshoot connectivity issues using packet captures and diagnostics',
      'Plan and execute network upgrades, expansions, and migrations',
      'Enforce network security through segmentation and access control lists',
      'Document network topology, IP addressing, and configuration standards',
    ],
  },
  {
    matches: ['frontend developer', 'front end developer', 'front-end developer', 'ui developer'],
    title: 'Frontend Developer',
    summary: 'Specialises in building user interfaces that run in web browsers or mobile webviews. Transforms design mockups into responsive, accessible, and performant UI components using HTML, CSS, and JavaScript frameworks.',
    tasks: [
      'Build reusable UI components with React, Angular, Vue, or similar',
      'Ensure cross-browser compatibility and responsive layout across devices',
      'Optimise page load performance (code splitting, lazy loading, caching)',
      'Consume REST/GraphQL APIs and manage application state',
      'Write unit and integration tests for UI code',
      'Collaborate with UX designers on interaction design and accessibility',
    ],
  },
  {
    matches: ['backend developer', 'backend engineer', 'back end developer', 'back-end developer', 'server side developer'],
    title: 'Backend Developer',
    summary: 'Builds the server-side logic, APIs, and data layers that power applications. Focuses on performance, security, and reliability of the services that frontend clients and third-party integrations call.',
    tasks: [
      'Design and implement REST or GraphQL APIs',
      'Write business logic, microservices, and background workers',
      'Model and manage databases (SQL and NoSQL)',
      'Ensure data security, authentication, and access control',
      'Optimise query and service performance under load',
      'Deploy and monitor backend services in production',
    ],
  },
  {
    matches: ['full stack developer', 'full-stack developer', 'fullstack developer'],
    title: 'Full Stack Developer',
    summary: 'Works across the entire application stack — from database and server-side API to browser-rendered UI. Provides end-to-end ownership of features and can context-switch between frontend and backend as needed.',
    tasks: [
      'Implement features across both frontend and backend codebases',
      'Design database schemas and build REST/GraphQL APIs',
      'Build and style UI components to match design specifications',
      'Set up or contribute to CI/CD pipelines and deployments',
      'Review code across the full stack for quality and security',
      'Optimise both server and client-side performance',
    ],
  },
  {
    matches: ['mobile developer', 'ios developer', 'android developer', 'mobile app developer'],
    title: 'Mobile App Developer',
    summary: 'Designs and builds applications for iOS and Android devices using native (Swift/Kotlin) or cross-platform (Flutter/React Native) frameworks. Focuses on smooth UX, device API integration, and app store delivery.',
    tasks: [
      'Build native or cross-platform mobile apps (Swift, Kotlin, Flutter, React Native)',
      'Integrate device features: camera, GPS, push notifications, biometrics',
      'Consume backend APIs and handle offline-first data synchronisation',
      'Optimise app performance, battery consumption, and memory usage',
      'Publish and manage releases on the App Store and Google Play',
      'Write unit and UI tests and triage crash reports',
    ],
  },
  {
    matches: ['test automation engineer', 'automation tester'],
    title: 'Test Automation Engineer',
    summary: 'Designs and maintains automated test suites that verify software behaviour continuously across the development lifecycle. Accelerates delivery by making regression and integration testing fast and reliable.',
    tasks: [
      'Design and implement automated test frameworks (Selenium, Playwright, Cypress, Robot Framework)',
      'Write end-to-end, integration, and API tests',
      'Integrate test suites into the CI/CD pipeline',
      'Analyse test failures, triage flaky tests, and drive fixes',
      'Define test coverage strategies with developers and QA leads',
      'Report on test coverage, pass rates, and quality trends',
    ],
  },
  {
    matches: ['qa engineer', 'quality assurance engineer', 'software tester', 'quality engineer software'],
    title: 'QA Engineer / Software Tester',
    summary: 'Ensures software products meet quality standards before release by planning and executing test scenarios, filing precise bug reports, and progressively automating repetitive tests.',
    tasks: [
      'Design and execute manual test cases for features and regression',
      'Write clear, reproducible bug reports with steps and severity',
      'Build and maintain automated test scripts as the product matures',
      'Define acceptance criteria with developers and product managers',
      'Perform exploratory, performance, and usability testing',
      'Track defect metrics and test coverage across releases',
    ],
  },
  {
    matches: ['software engineer', 'software developer', 'programmer', 'application developer', 'web developer'],
    title: 'Software Engineer / Developer',
    summary: 'Designs, builds, and maintains software applications and systems across the full development lifecycle. Turns product requirements into reliable, tested, and maintainable code.',
    tasks: [
      'Write clean, well-tested code following team standards and patterns',
      'Participate in design and code reviews to maintain code quality',
      'Debug and resolve defects across the stack',
      'Collaborate with product managers, designers, and QA in agile sprints',
      'Contribute to architectural decisions and technical documentation',
      'Continuously improve delivery practices through retrospectives',
    ],
  },
  {
    matches: ['ux designer', 'ui designer', 'ui ux designer', 'product designer', 'ux researcher'],
    title: 'UX / UI Designer',
    summary: 'Creates digital products that are intuitive, accessible, and visually consistent — combining user research, wireframing, and high-fidelity prototyping to guide the development team.',
    tasks: [
      'Conduct user research through interviews, surveys, and usability tests',
      'Create user personas, journey maps, and information architecture',
      'Design wireframes, prototypes, and high-fidelity mockups in Figma or Sketch',
      'Develop and maintain a shared design system and component library',
      'Hand off specifications to developers and review the built implementation',
      'Measure UX outcomes (task completion, NPS, session recordings)',
    ],
  },
  {
    matches: ['technical support', 'it support', 'helpdesk', 'help desk', 'service desk'],
    title: 'Technical Support / IT Support',
    summary: 'The first point of contact for users experiencing hardware, software, or connectivity problems. Diagnoses, resolves, or escalates issues to keep employees and customers productive.',
    tasks: [
      'Respond to helpdesk tickets via phone, email, and remote desktop tools',
      'Diagnose and resolve hardware, software, and network issues',
      'Set up and configure workstations, peripherals, and mobile devices',
      'Manage user accounts and permissions in Active Directory / Microsoft 365',
      'Escalate complex issues to L2/L3 support with clear documentation',
      'Maintain the IT knowledge base with solution articles',
    ],
  },
  // ------------------------------------------------------------------ Product & Project
  {
    matches: ['product manager'],
    title: 'Product Manager',
    summary: 'Owns the product vision, roadmap, and delivery — translating user needs and business goals into a prioritised backlog. Acts as the bridge between engineering, design, marketing, and stakeholders.',
    tasks: [
      'Define and maintain the product roadmap aligned with business strategy',
      'Write user stories, epics, and acceptance criteria for the engineering team',
      'Conduct user research and synthesise customer feedback',
      'Prioritise the backlog using data, business value, and effort estimates',
      'Track product KPIs and iterate based on usage data and experiments',
      'Align stakeholders on scope, timelines, and trade-offs',
    ],
  },
  {
    matches: ['project manager'],
    title: 'Project Manager',
    summary: 'Plans, executes, and closes projects on time and within budget. Manages scope, risks, resources, and communication between all parties involved in delivering a defined outcome.',
    tasks: [
      'Create and maintain project plans, timelines, budgets, and RACI matrices',
      'Identify, assess, and mitigate project risks and issues',
      'Facilitate stakeholder communication and regular status reporting',
      'Manage scope creep and handle change requests through a formal process',
      'Coordinate cross-functional teams and resolve dependency conflicts',
      'Conduct post-project reviews and capture lessons learned',
    ],
  },
  {
    matches: ['scrum master', 'agile coach'],
    title: 'Scrum Master / Agile Coach',
    summary: 'Serves a development team by facilitating agile ceremonies, removing impediments, and coaching on Scrum practices. Protects the team\'s focus and promotes continuous improvement.',
    tasks: [
      'Facilitate daily stand-ups, sprint planning, reviews, and retrospectives',
      'Remove blockers and coordinate with external teams and stakeholders',
      'Coach team members and the organisation on agile principles and Scrum',
      'Track and improve team velocity, capacity, and sprint health metrics',
      'Support the Product Owner with backlog refinement and story sizing',
      'Drive a culture of continuous improvement and psychological safety',
    ],
  },
  {
    matches: ['business analyst'],
    title: 'Business Analyst',
    summary: 'Analyses business processes and requirements, translating them into clear specifications for technical teams. Acts as the bridge between business stakeholders and the development team.',
    tasks: [
      'Elicit and document business requirements through workshops and interviews',
      'Create process models, use-case diagrams, and functional specifications',
      'Analyse existing systems and identify process improvement opportunities',
      'Facilitate requirement sign-off and manage changes throughout the project',
      'Support testing by defining acceptance criteria and reviewing test scenarios',
      'Produce data flow diagrams, gap analyses, and impact assessments',
    ],
  },
  // ------------------------------------------------------------------ Finance
  {
    matches: ['financial controller', 'finance controller'],
    title: 'Financial Controller',
    summary: 'Oversees the accounting function and ensures accurate, timely financial reporting. Owns the month-end close, management accounts, and statutory compliance.',
    tasks: [
      'Manage the month-end and year-end financial close process',
      'Prepare and review management accounts and board-level reports',
      'Oversee balance sheet reconciliations and journal entry approvals',
      'Ensure compliance with IFRS, local GAAP, and tax regulations',
      'Manage relationships with external auditors and tax advisers',
      'Lead and develop the accounting and finance team',
    ],
  },
  {
    matches: ['financial analyst', 'finance analyst'],
    title: 'Financial Analyst',
    summary: 'Provides financial insights and forecasts to support business decisions. Analyses historical data, builds financial models, and presents findings to management.',
    tasks: [
      'Build and maintain financial models: budgets, forecasts, and DCF valuations',
      'Analyse variances between actuals and plan, explaining key drivers',
      'Prepare management presentations and board-ready financial packs',
      'Support annual business planning and quarterly reforecasting cycles',
      'Conduct market, competitor, and scenario analysis',
      'Collaborate with accounting on month-end close and data accuracy',
    ],
  },
  {
    matches: ['accountant', 'bookkeeper'],
    title: 'Accountant',
    summary: 'Records, classifies, and reports financial transactions to maintain accurate books. Manages day-to-day accounting operations and supports tax reporting and audit processes.',
    tasks: [
      'Process supplier invoices, customer payments, and bank reconciliations',
      'Prepare and post journal entries across the general ledger',
      'Assist with month-end close and management account preparation',
      'Support VAT, corporate tax, and statutory filing processes',
      'Maintain fixed asset registers and depreciation schedules',
      'Assist with internal and external audit requests and queries',
    ],
  },
  {
    matches: ['auditor', 'internal auditor'],
    title: 'Auditor / Internal Auditor',
    summary: 'Independently evaluates the effectiveness of internal controls, risk management, and governance, providing assurance to management and the board that the organisation operates correctly.',
    tasks: [
      'Plan and execute risk-based audit assignments across the business',
      'Evaluate controls over financial reporting, operations, and compliance',
      'Document findings and draft clear, actionable audit reports',
      'Follow up on management\'s implementation of previous recommendations',
      'Work with external auditors during the annual statutory audit',
      'Contribute to developing the risk-based annual audit plan',
    ],
  },
  {
    matches: ['compliance officer', 'compliance specialist'],
    title: 'Compliance Officer',
    summary: 'Ensures the organisation adheres to legal regulations, internal policies, and industry standards. Identifies compliance risks and works with business units to address them.',
    tasks: [
      'Monitor regulatory developments (GDPR, NIS2, AML, SOX) and assess impact',
      'Conduct compliance audits and gap assessments against standards',
      'Develop, update, and communicate internal policies and procedures',
      'Train employees on compliance requirements and ethical conduct',
      'Liaise with regulators, managing submissions and inspection responses',
      'Report compliance status and risk exposure to senior management',
    ],
  },
  // ------------------------------------------------------------------ Engineering (non-IT)
  {
    matches: ['mechanical engineer', 'mechanical design engineer'],
    title: 'Mechanical Engineer',
    summary: 'Designs, analyses, and improves mechanical systems and components for products or industrial applications. Balances performance requirements, manufacturing feasibility, and cost from concept through to production.',
    tasks: [
      'Create 3D models and engineering drawings (SolidWorks, CATIA, AutoCAD)',
      'Perform stress, thermal, and tolerance analysis (FEA/CFD)',
      'Define GD&T and manufacturing tolerances for precision parts',
      'Collaborate with production, quality, and supply chain teams',
      'Manage prototype builds, testing, and design iterations',
      'Maintain engineering documentation and ECO change records',
    ],
  },
  {
    matches: ['electrical engineer', 'electronics engineer'],
    title: 'Electrical / Electronics Engineer',
    summary: 'Designs and develops electrical systems, circuits, and components — from requirement specification through schematic capture, PCB layout, and verification testing.',
    tasks: [
      'Design electrical schematics and PCB layouts (Altium, Eagle, Cadence)',
      'Select and specify components considering performance, cost, and availability',
      'Perform electrical simulations and worst-case fault analysis',
      'Test and commission prototypes against functional specifications',
      'Ensure compliance with EMC, safety, and CE/UL standards',
      'Collaborate with firmware and mechanical engineers on full system integration',
    ],
  },
  {
    matches: ['automation engineer', 'plc engineer', 'process automation', 'industrial automation'],
    title: 'Automation / PLC Engineer',
    summary: 'Programs and maintains automated production systems using PLCs, SCADA platforms, and industrial robots to improve manufacturing efficiency and reduce manual intervention.',
    tasks: [
      'Program PLCs and motion controllers (Siemens TIA Portal, Allen-Bradley, Schneider)',
      'Configure and maintain SCADA systems, HMIs, and operator panels',
      'Design automation sequences and interlocks for production lines',
      'Diagnose and resolve electrical, mechanical, and software faults rapidly',
      'Drive OEE improvement projects through automation and process analysis',
      'Document control system architecture, I/O lists, and function descriptions',
    ],
  },
  {
    matches: ['civil engineer', 'structural engineer'],
    title: 'Civil / Structural Engineer',
    summary: 'Plans and oversees the design and construction of infrastructure — roads, bridges, buildings, drainage, and utilities — ensuring structural integrity, safety, and regulatory compliance.',
    tasks: [
      'Develop structural and civil designs using AutoCAD, Revit, or Tekla',
      'Produce technical specifications, calculations, and engineering drawings',
      'Coordinate with architects, contractors, and site supervisors',
      'Conduct site inspections and enforce quality control procedures',
      'Manage project schedules, budgets, and change orders',
      'Ensure compliance with building codes, Eurocodes, and safety regulations',
    ],
  },
  {
    matches: ['quality assurance engineer', 'quality engineer', 'quality control', 'qa specialist manufacturing'],
    title: 'Quality Assurance Engineer (Manufacturing)',
    summary: 'Ensures manufactured products meet design specifications and customer requirements through audits, inspections, and process control. Applies methodologies like Six Sigma and IATF 16949.',
    tasks: [
      'Conduct incoming, in-process, and final product inspections',
      'Manage non-conformance reports (NCRs) and corrective action (CAPA) processes',
      'Support customer and third-party audits (IATF 16949, ISO 9001)',
      'Lead root cause analysis using 8D, 5-Why, and Ishikawa methods',
      'Develop control plans, FMEA, and measurement system analyses (MSA)',
      'Monitor process capability (Cp, Cpk) and drive continuous improvement',
    ],
  },
  // ------------------------------------------------------------------ Sales & Marketing
  {
    matches: ['account manager', 'key account manager'],
    title: 'Account Manager',
    summary: 'Manages ongoing client relationships to ensure satisfaction, retain contracts, and grow revenue within an assigned portfolio of accounts.',
    tasks: [
      'Build and maintain strong long-term relationships with client contacts',
      'Identify upsell and cross-sell opportunities within existing accounts',
      'Negotiate contract renewals, amendments, and commercial terms',
      'Coordinate internal teams (delivery, support, product) to meet client needs',
      'Track account health KPIs and report on retention and growth metrics',
      'Resolve client escalations promptly and prevent churn',
    ],
  },
  {
    matches: ['sales representative', 'sales consultant', 'sales executive'],
    title: 'Sales Representative',
    summary: 'Proactively generates new business by identifying prospects, pitching products or services, and closing deals within an assigned territory, vertical, or product line.',
    tasks: [
      'Prospect and qualify new leads through calls, emails, and events',
      'Conduct product demonstrations, discovery calls, and proposals',
      'Negotiate pricing, scope, and contract terms to close deals',
      'Maintain an accurate CRM pipeline with up-to-date deal data (Salesforce, HubSpot)',
      'Achieve or exceed monthly and quarterly revenue targets',
      'Report on pipeline health and forecast accurately to management',
    ],
  },
  {
    matches: ['digital marketing manager', 'marketing manager', 'seo specialist', 'sem specialist', 'content marketing'],
    title: 'Digital Marketing Manager',
    summary: 'Plans and executes online marketing campaigns across SEO, SEM, social media, email, and content channels to drive traffic, leads, and brand awareness.',
    tasks: [
      'Define and execute the digital marketing strategy and budget',
      'Manage SEO/SEM campaigns (Google Ads, Meta Ads, Bing Ads)',
      'Plan and schedule organic social media content across platforms',
      'Run email marketing campaigns, nurture sequences, and A/B tests',
      'Analyse performance with Google Analytics, GA4, and attribution tools',
      'Manage agency, freelancer, and platform relationships',
    ],
  },
  // ------------------------------------------------------------------ BPO & Support
  {
    matches: ['customer support specialist', 'customer service', 'customer success', 'customer care'],
    title: 'Customer Support Specialist',
    summary: 'The primary point of contact for customers with questions, issues, or complaints. Ensures fast, high-quality resolutions while feeding insights back to improve the product and process.',
    tasks: [
      'Respond to customer queries via phone, email, chat, or ticketing system',
      'Diagnose customer issues and resolve or escalate with full context',
      'Log and track all interactions in the CRM or help desk (Zendesk, Salesforce)',
      'Follow up to confirm resolution and customer satisfaction',
      'Identify recurring issues and escalate patterns to product and engineering',
      'Meet SLA response times and CSAT / NPS performance targets',
    ],
  },
  // ------------------------------------------------------------------ HR
  {
    matches: ['hr specialist', 'human resources', 'recruiter', 'talent acquisition', 'hr manager'],
    title: 'HR Specialist / Recruiter',
    summary: 'Manages the recruitment process and employee lifecycle activities — from talent sourcing and interviewing to onboarding, payroll, and performance management. The operational backbone of people management.',
    tasks: [
      'Write job descriptions and post vacancies across job boards and LinkedIn',
      'Screen CVs, conduct phone screens, and coordinate interview processes',
      'Manage candidate pipelines and the ATS (BambooHR, Workday, SAP SuccessFactors)',
      'Coordinate onboarding of new hires and probation processes',
      'Handle HR administration: contracts, payroll inputs, absence tracking',
      'Support performance review cycles and employee engagement initiatives',
    ],
  },
  // ------------------------------------------------------------------ Healthcare
  {
    matches: ['registered nurse', 'nurse', 'nursing'],
    title: 'Registered Nurse',
    summary: 'Provides direct patient care under the supervision of physicians — administering treatments, monitoring health status, and supporting patient and family wellbeing throughout the care journey.',
    tasks: [
      'Assess and monitor patients\' vital signs, symptoms, and health status',
      'Administer medications, IV therapy, and clinical treatments as prescribed',
      'Perform wound care, catheter care, and other bedside procedures',
      'Coordinate care across the multidisciplinary team (doctors, physios, dietitians)',
      'Educate patients and families on diagnoses, care plans, and discharge',
      'Document all care activities accurately in the patient record system',
    ],
  },
  {
    matches: ['physician', 'doctor', 'medical doctor'],
    title: 'Physician / Doctor',
    summary: 'Diagnoses and treats medical conditions, prescribes therapies, and manages patients\' overall health — in primary care, hospital, or specialist clinic settings.',
    tasks: [
      'Conduct patient consultations, history-taking, and physical examinations',
      'Order and interpret diagnostic tests (blood work, imaging, ECG)',
      'Diagnose conditions and formulate evidence-based treatment plans',
      'Prescribe and review medications, adjusting for response and side-effects',
      'Refer to specialist colleagues and coordinate multidisciplinary care',
      'Maintain accurate, timely medical records and documentation',
    ],
  },
  {
    matches: ['physiotherapist', 'physical therapist'],
    title: 'Physiotherapist',
    summary: 'Assesses and treats patients with musculoskeletal injuries, neurological conditions, or post-surgical impairments through exercise therapy, manual techniques, and rehabilitation programmes.',
    tasks: [
      'Conduct initial assessments and set measurable rehabilitation goals',
      'Design and supervise individualised exercise programmes',
      'Apply manual therapy, joint mobilisation, and soft tissue techniques',
      'Use electrotherapy, ultrasound, and other modalities as appropriate',
      'Monitor progress, adapt treatment plans, and discharge safely',
      'Educate patients on injury prevention and home exercise routines',
    ],
  },
  // ------------------------------------------------------------------ Logistics
  {
    matches: ['supply chain manager', 'supply chain coordinator', 'operations manager supply'],
    title: 'Supply Chain Manager',
    summary: 'Oversees the end-to-end flow of goods — from raw material sourcing through manufacturing and distribution to the end customer — optimising cost, speed, and reliability across every link.',
    tasks: [
      'Manage supplier relationships, contracts, and performance reviews',
      'Build demand forecasts and manage inventory levels to prevent stockouts and overstock',
      'Coordinate procurement, logistics, and production planning teams',
      'Identify and mitigate supply chain disruption risks',
      'Implement and optimise ERP and supply chain management systems (SAP)',
      'Track KPIs: OTIF, inventory turns, lead times, and total cost to serve',
    ],
  },
  {
    matches: ['logistics coordinator', 'logistics specialist', 'freight coordinator', 'transport coordinator'],
    title: 'Logistics Coordinator',
    summary: 'Coordinates the movement of goods between suppliers, warehouses, and customers — ensuring shipments leave on time, documentation is correct, and exceptions are resolved quickly.',
    tasks: [
      'Book and track shipments across road, sea, air, and rail carriers',
      'Liaise with freight forwarders, carriers, and customs brokers',
      'Prepare and verify shipping documents (CMR, AWB, Bill of Lading, customs declarations)',
      'Monitor delivery performance and proactively resolve delays or damages',
      'Update the WMS/TMS with shipment status and event data',
      'Report on logistics KPIs, carrier performance, and freight costs',
    ],
  },
  {
    matches: ['warehouse operative', 'warehouse worker', 'warehouse associate', 'forklift operator'],
    title: 'Warehouse Operative',
    summary: 'Manages the physical receipt, storage, picking, packing, and dispatch of goods within a warehouse or distribution centre, following safety and accuracy procedures.',
    tasks: [
      'Receive inbound deliveries and verify quantities against purchase orders',
      'Putaway stock to designated locations using WMS or handheld scanners',
      'Pick, pack, and dispatch customer orders accurately and on time',
      'Operate forklifts, pallet trucks, and other warehouse equipment safely',
      'Conduct cycle counts and participate in periodic stock takes',
      'Maintain a clean, organised, and safe working environment (5S)',
    ],
  },
];

export default ROLES;
